name: Continuous Integration & Storybook Deployment

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - feat/*
      - fix/*
      - refactor/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build test
        run: npm run build

  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Install Dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          # Deploy only the storybook-static folder
          STORYBOOK_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm --cwd ./storybook-static)
          
          # Extract the URL from the Vercel output
          STORYBOOK_URL=$(echo $STORYBOOK_URL | tail -n1)

          # Set the URL as an environment variable to use in the next steps
          echo "STORYBOOK_URL=$STORYBOOK_URL" >> $GITHUB_ENV
          
          # Optionally, add a comment with the Storybook URL to the PR
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\": \"Storybook URL: $STORYBOOK_URL\"}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
